title:              Advanced Applications of Next Generation Sequencing and Bioinformatics in Food Safety
email:              cfs@ucd.ie
description:        Scientific Programme for the workshop "Advanced Applications of Next Generation Sequencing in Food Safety"
author:             Stellenbosch University, South Africa and University College Dublin, Ireland

baseurl:            "/"
url:                "https://macgenomegue.github.io"

# Social Profiles
twitter_username:   SBootstrap
github_username:    StartBootstrap
facebook_username:  StartBootstrap
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
